// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgJNrkHAx4lQ9NRyLHY13IBqAwfMtHTbU',
    appId: '1:524572247498:web:542ec9ce9eed23b2b47b33',
    messagingSenderId: '524572247498',
    projectId: 'khadamat-f5821',
    authDomain: 'khadamat-f5821.firebaseapp.com',
    storageBucket: 'khadamat-f5821.appspot.com',
    measurementId: 'G-E8G4ZW4DVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZYis5myZt68bMzEtL3jyahFovvhrYuo',
    appId: '1:524572247498:android:e2a699700d7085dbb47b33',
    messagingSenderId: '524572247498',
    projectId: 'khadamat-f5821',
    storageBucket: 'khadamat-f5821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkSUNFfMgoxwFG1A5cTvc-SpztsXmLiI',
    appId: '1:524572247498:ios:3b2659d17a85ac65b47b33',
    messagingSenderId: '524572247498',
    projectId: 'khadamat-f5821',
    storageBucket: 'khadamat-f5821.appspot.com',
    iosBundleId: 'com.example.khadamatDashboard',
  );
}
